spring:
  application:
    name: CONFIG-SERVER
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:/IdeaWorkspace

server:
  port: 8888

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8768/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: localhost